### ISSUE TITLE
Repair Cost bug

### ISSUE THREAD

**Issue by CaliDreams** [Zrips/CMI-API#10]
I don't wish to have my players pay a fee to use /cmi repair - so I have that setting off in the config:

  Repair:
    # When item costs money, player will be required to confirm repair action by clicking message in chat
    Confirmation: true
    # When set to true, item repair with /cmi repair will cost money depending on setup
    # Player who performs command will pay repair cost
    # If command gets performed from console, then player whose items are repaired will be paying
    CostsMoney: false

However, since this last update, it is charging them regardless: [https://imgur.com/a/5tdK6Si](url)
It's not asking for confirmation either, which I do have on. Am I missing something?

Using Paper 1.14.4
CMI 8.6.13.0

**Comment by ACluco1** [comment]
Still an issue, could you please fix it? I want my players to pay for repairs, but i dont want to make administrators pay for it.

**Comment by Zrips** [comment]
resolved
