### ISSUE TITLE
Missing Hologram API methods

### ISSUE THREAD

**Issue by RedstoneGamer123** [Zrips/CMI-API#13]
Unlike shown in the Hologram API examples, ALL - CMIHologram.makePersistent(), .remove(), .disable(), and .enable() do NOT exist in the latest CMIAPI jar.

**Comment by RedstoneGamer123** [comment]
Update on this.

The methods seem to have been moved to another class, I finally found them, but this really should be updated on the website.

**Comment by mrfloris** [comment]
Update: (Sorry for the delay) <https://www.zrips.net/cmi/api/>

The website I noticed now has the following listed for holograms:
<img width="297" alt="Screen-Shot 2023-02-01 at 15 56 51" src="https://user-images.githubusercontent.com/28841349/216077777-d71392cf-84fe-4137-9ed4-c3fbf627f7d2.png">

If anything's still missing feel free to let me know.
