### ISSUE TITLE
Add CMIPlayerWarnEvent

### ISSUE THREAD

**Issue by RookieAND** [Zrips/CMI-API#19]
I try to make some additional message and alert in my discord server so I try to find the API event but sadly CMI doesn't have it.

So If you add Warn Event (fired when player get or remove warn point) I truly glad.

**Comment by mrfloris** [comment]
Hey there, 

I see the repo had an update and there's a new jar under releases, and the website on zrips.net now mentions:
```
CMIPlayerWarnEvent – Fired when player gets a warning
```
Hopefully this is what you needed.
