### ISSUE TITLE
List of colors for /cmi me color permissions?

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/CMI-API#2]
It's not actually color codes, which is offputting (e.g. &a, &b etc), but the actual word of color (red, darkred).

I've looked and looked and cannot find a full list of these colors/formats in their word form anywhere. Please help? There's only so much guessing I can do x.x

**Comment by Zrips** [comment]
Its generic ChatColor enum, get its name with .name() convert to lowercase and replace "_" to ""
