### ISSUE TITLE
Add maven/gradlew build files so that CMI API can be used with jitpack

### ISSUE THREAD

**Issue by EnderGamingFilms** [Zrips/CMI-API#31]
Could you please add build configurations to the repo so website can generate artifacts?

**Comment by mrfloris** [comment]
This seems to be the same request as here: https://github.com/Zrips/CMI-API/issues/6

Also, it seems the repository has received some work yesterday, I see mentions of Maven.

**Comment by mrfloris** [comment]
Update: The repository has received some work yesterday, I see there's been new releases here: https://github.com/Zrips/CMI-API/releases
