### ISSUE TITLE
Will CMI-API ever have a maven repo we can use?

### ISSUE THREAD

**Issue by FireML** [Zrips/CMI-API#52]
None of the JitPack builds have succeeded, and i'd rather not put the jar file in my code for cleanliness reasons.

**Comment by regix1** [comment]
https://jitpack.io/p/Zrips/CMI-API

        <dependency>
            <groupId>com.github.Zrips</groupId>
            <artifactId>CMI-API</artifactId>
            <version>9.7.4.1</version>
        </dependency>
