### ISSUE TITLE
Maven artifact + repository

### ISSUE THREAD

**Issue by Phoenix616** [Zrips/CMI-API#6]
It would really help integrating with your resource if you would offer a maven repository that contains an artifact of your API jar.

**Comment by TheFlagCourier** [comment]
GitHub Package Registry could definitely serve the necessary packages.

**Comment by lululombard** [comment]
Just a comment to say that I definitely need this for a better experience to make plugins that use CMI features

**Comment by SkytAsul** [comment]
Up! This would be amazing.

**Comment by FN-FAL113** [comment]
up

**Comment by andrew121410** [comment]
Yes, what he could just do is use Jitpack and make this use maven

**Comment by SkytAsul** [comment]
He just does not care... the support is pretty much inexistant for its plugin.

**Comment by mrfloris** [comment]
I just saw changes to the repository, it looks like it's being worked on, and I see mentions of Maven. Hopefully, this helps.

**Comment by Zrips** [comment]
Maven more or less got sorted out now and ready to be used
