### ISSUE TITLE
CMI-API fails to build.

### ISSUE THREAD

**Issue by MrAmos123** [Zrips/CMI-API#9]
Plugin using CMI-API fails to build even though it is added as an external jar, is there a further Maven dependency I'm missing?

**Comment by Zrips** [comment]
As you can see from commits, its quite old one and doesn't contain newest things which could result into issues. I cant really push out real plugin code and to make this empty shell example is tedious work for 3.5MB plugin each time i'm changing something. Send me pm on discord, will be faster conversation
